[package]
name = "eth-mapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.13.3"
ethers-rs = "0.2.3"
neo4rs = "0.6.0"
serde = "1.0.164"
