services:
  neo4j:
   image: neo4j:latest
   mem_limit: 12g
   mem_reservation: 12g
   ports:
      - "7474:7474"
      - "7687:7687"
   volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
   environment:
      - NEO4J_AUTH=neo4j/test12345
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache_size=2G
      - NEO4J_dbms_memory_transaction_total_max=5G

