#write a docker compose for establishing a neo4j docker container with persistent data using mounted volumes
version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/test12345
